### PR TITLE
Fixed the datetime date format issue

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
Fixes the Issue: https://github.com/open-admin-org/open-admin/issues/98

Also, the datetime format needs to be in accordance with: https://flatpickr.js.org/formatting/

### CODE REVIEW

**Comment by open-admin-org** [comment]
@SachinBahukhandi  thanks for the fix

**Comment by andrew-m-p** [comment]
The solution is partial (dont think it should not have been merged)

$this->options['format'] = $this->format; <--- wants php date format structure
$this->options['dateFormat'] = $this->format; <--- wants javascript date format structure

To make it work in my case italian date format I hacked it like this:
In date.php:

$this->options['dateFormat'] ='d/m/Y'; //hard coded needs to go from php format to javascript format

In my controller I had to do this:
 protected function form()     {

$form->date('date', __('Date'))->default(date('d-m-Y'))->format('DD/MM/YYYY')->customFormat(function ($date) {
            $dt=explode("-",$date);
            return  ($dt[2]."/".$dt[1]."/".$dt[0]) ;
        });;

an in app.php my locale is:

'locale' => 'it',

All very ugly...

Thanks for the reply and help

**Comment by SachinBahukhandi** [comment]
But what is the Italian date format?
And this was just a fix because it was not taking up the format. 
Maybe we could push a FR, if I am not wrong, You mean to set a global default date format right?

**Comment by andrew-m-p** [comment]
Italian date format is DD/MM/YYYY. I think a built in global date format makes sense.

$this->options['dateFormat'] < -   javascript format string "DD/MM/YYYY"
$this->options['format']  <-- php date format string "d/m/Y"

**Comment by andrew-m-p** [comment]
Correction

$this->options['dateFormat'] < - javascript format string "d/m/Y"
$this->options['format'] <-- php date format string "DD/MM/YYYY"

**Comment by SachinBahukhandi** [comment]
I suppose we're only using datepicker based on the JS Date format so using a PHP default date format would make sense?

**Comment by andrew-m-p** [comment]
I think it makes sense to use php date format and convert into javascript 

Also it would be usefull to add a function in date.php something like this:

if config("app.format") set then $format = config("app.format") else $format='YYYY-MM-DD'

Instead of :  protected $format = 'YYYY-MM-DD';

It would also be better to open this ticket again it needs discussion and fixing

Not hearing much from admins are they not interested in their project any more?

**Comment by SachinBahukhandi** [comment]
Not sure about the admins, but I think on my perspective it would be an overhead to ask the user to post a PHP-based time format as it has been mentioned clearly here: https://open-admin.org/docs/en/model-form-fields#date-time-fields

But yeah it would be great if the user is allowed to enter php based date-time formats as the IDE would significantly help them.

Also, yes the config should be published and there we could maybe provide the default date format like you suggested.

**Comment by open-admin-org** [comment]
Will take a more detailed look at this next week. It indeed needs some rethinking to allow other formats. Thanks for all the feedback.

**Pull request merged**
